import type {
  ApiResponse,
  PaginatedResponse,
  UserRole,
  Region,
  TransportMode,
  CustomsStatus,
  LogisticsExceptionType,
  ReturnLiability,
  ApprovalStatus,
  WorkOrderPriority,
  WorkOrderType,
  User,
  Warehouse,
  Product,
  Inventory,
  TransferOrder,
  TransferItem,
  TransferSuggestion,
  Order,
  OrderItem,
  WarehouseOption,
  FulfillmentRecommendation,
  CustomsDeclaration,
  CustomsTrajectory,
  WorkOrder,
  LogisticsTracking,
  LogisticsTrajectoryPoint,
  LogisticsException,
  Compensation,
  CompensationBreakdown,
  ReturnRecord as SharedReturnRecord,
  Refund,
  ApprovalFlow,
  SystemRule,
  DashboardKPI,
  WarehouseTurnover,
  PortClearanceTime,
  SalesTrendItem,
  LogisticsExceptionPoint,
  InventoryAlert,
  SupplyChainMetrics,
  CustomsDocument,
  LoginRequest,
  LoginResponse,
} from '../shared/types';

export type {
  ApiResponse,
  PaginatedResponse,
  UserRole,
  Region,
  TransportMode,
  CustomsStatus,
  LogisticsExceptionType,
  ReturnLiability,
  ApprovalStatus,
  WorkOrderPriority,
  WorkOrderType,
  User,
  Warehouse,
  Product,
  Inventory,
  TransferOrder,
  TransferItem,
  TransferSuggestion,
  Order,
  OrderItem,
  WarehouseOption,
  FulfillmentRecommendation,
  CustomsDeclaration,
  CustomsTrajectory,
  WorkOrder,
  LogisticsTracking,
  LogisticsTrajectoryPoint,
  LogisticsException,
  Compensation,
  CompensationBreakdown,
  Refund,
  ApprovalFlow,
  SystemRule,
  DashboardKPI,
  WarehouseTurnover,
  PortClearanceTime,
  SalesTrendItem,
  LogisticsExceptionPoint,
  InventoryAlert,
  SupplyChainMetrics,
  CustomsDocument,
  LoginRequest,
  LoginResponse,
};

export type ReturnRecord = SharedReturnRecord;

export interface InventoryChange {
  before: number;
  after: number;
  change: number;
  reason: string;
}

export type ReturnRecordWithInventory = ReturnRecord & {
  inventoryChange?: InventoryChange;
};
